### ISSUE TITLE
set_extension() got an unexpected keyword argument 'force'

### ISSUE THREAD

**Issue by elisasongintegr8** [Liebeck/spacy-sentiws#1]
Hi,

I've followed your instruction, but got an error msg: set_extension() got an unexpected keyword argument 'force'

Can you pls help me with that?

**Comment by elisasongintegr8** [comment]
I found the problem: in spacy, Token.set_extension doesn't have 'force' as input.

https://spacy.io/api/token

**Comment by Liebeck** [comment]
What is your spaCy version? They introduced the force parameter in 2.0.3, I think.
According to https://github.com/explosion/spaCy/blob/master/spacy/tokens/token.pyx#L31-L34 and  https://github.com/explosion/spaCy/blob/master/spacy/errors.py#L238-L239 the force parameter should still be in use.

**Comment by elisasongintegr8** [comment]
Hi, thanks for your msg. My spacy version is 2.0.10       
I deleted the ‘force’, and I don’t have any problem with your script anymore.

**Comment by Liebeck** [comment]
Ok, percect. Might be related to https://github.com/explosion/spaCy/issues/2073 which was fixed in 2.0.11

I had to use the force parameter since I created multiple pipeline instances and there was an issue with settings extensions globally
