### ISSUE TITLE
pip install spacy-sentiws installs an older version

### ISSUE THREAD

**Issue by shubhamk8597** [Liebeck/spacy-sentiws#5]
pip install spacy-sentiws installs an older version where it is not compatible with the spacy 3. How can I get this git repo in pip installation?

**Comment by anagarlau** [comment]
Hi. I have the same issues regarding the installation with pip.  Could you please explain how to get the actual version? thanks

**Comment by Liebeck** [comment]
@anagarlau  I haven't worked with spaCy for a while. I already accepted a pull request which should bump successfully to spaCy 3. For now, you need download the source from the GitHub repository.
I hope that I found the time to relearn how to upload a need package version during the Christmas holidays. If someone can link me working tutorial, that would be much appreciated. I'm not sure if I can find my credentials.

**Comment by Liebeck** [comment]
@shubhamk8597 @anagarlau  I finally pushed the spaCy 3 version to PyPI

**Comment by anagarlau** [comment]
Thanks, it s working perfectly now 😊
