### ISSUE TITLE
Can't add sentiws to spacy pipeline

### ISSUE THREAD

**Issue by marvisSydow** [Liebeck/spacy-sentiws#6]
import spacy
from spacy_sentiws import spaCySentiWS
nlp = spacy.load('de_core_news_sm')
nlp.add_pipe('sentiws', config={'sentiws_path': 'data/sentiws/'})

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_9632\291549605.py in <module>
      3 
      4 nlp = spacy.load('de_core_news_sm')
----> 5 nlp.add_pipe('sentiws', config={'sentiws_path': 'data/sentiws/'})

~\PythonProgramming\Anaconda\lib\site-packages\spacy\language.py in add_pipe(self, factory_name, name, before, after, first, last, source, config, raw_config, validate)
    799                     lang_code=self.lang,
    800                 )
--> 801             pipe_component = self.create_pipe(
    802                 factory_name,
    803                 name=name,

~\PythonProgramming\Anaconda\lib\site-packages\spacy\language.py in create_pipe(self, factory_name, name, config, raw_config, validate)
    659                 lang_code=self.lang,
    660             )
--> 661             raise ValueError(err)
    662         pipe_meta = self.get_factory_meta(factory_name)
    663         # This is unideal, but the alternative would mean you always need to

ValueError: [E002] Can't find factory for 'sentiws' for language German (de). This usually happens when spaCy calls `nlp.create_pipe` with a custom component name that's not registered on the current language class. If you're using a Transformer, make sure to install 'spacy-transformers'. If you're using a custom component, make sure you've added the decorator `@Language.component` (for function components) or `@Language.factory` (for class components).

Available factories: attribute_ruler, tok2vec, merge_noun_chunks, merge_entities, merge_subtokens, token_splitter, doc_cleaner, parser, beam_parser, lemmatizer, trainable_lemmatizer, entity_linker, ner, beam_ner, entity_ruler, tagger, morphologizer, senter, sentencizer, textcat, spancat, future_entity_ruler, span_ruler, textcat_multilabel

**Comment by Liebeck** [comment]
@marvisSydow I haven't used spaCy 3, unfortunately. Can you provide a pull request to fix the issue?

Just to make sure: Are you using the source code from the Git repository which has been updated to spaCy 3? The pip version is lagging behind, at the moment

**Comment by marvisSydow** [comment]
Hi, yes. I installed the current repo on the command line from the compressed archive. Is this ok?

**Comment by Liebeck** [comment]
@marvisSydow I'm not sure how to install from a compressed archive. Just don't use pip for spaCy 3 (see https://github.com/Liebeck/spacy-sentiws/issues/5)

I guess you used the latest code but it's not compatible anymore? Most likely, it will be a three line fix. Would you mind taking a quick look and if you are able to solve it: Could you provide a pull request? 😀

**Comment by marvisSydow** [comment]
First of all - I am fairly new to python.
i installed the repo with **python -m pip install -e <path to unzipped folder>**. The installation succeeded but it s not working still. 
before I do the pull request, could you please expand on what the right installation command is for this repo?

**Comment by Liebeck** [comment]
@marvisSydow I finally pushed the spaCy 3 version to PyPI. Can you try again?
